fix linting (#3)

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -20,3 +20,11 @@ jobs:
 
             - name: Test
               run: yarn test
+
+            - name: Check if dist is up to date
+              run: |
+                  yarn build
+                  if [ "$(git diff --name-only dist)" ]; then
+                      echo "::error::The dist file is not up to date. Please run 'yarn build' and commit the changes before pushing."
+                      exit 1
+                  fi
